blog/urls.py
from django.conf.urls import url
from blog import views


urlpatterns = [
   url(r'^$',views.list,name='list'),
   url(r'^(?P<article_id>[0-9]+)/$',views.detail,name='detail'),
]

leettest/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from leettest import settings



#add static resources config when settings.DEBUG=FALSE
from django.conf import settings 
if settings.DEBUG is False:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT,
        }),
    )


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'leettest.views.home', name='home'),
    # url(r'^leettest/', include('leettest.foo.urls')),
   
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    (r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
            
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),

        
    #config the website index
    url('^$','index.views.index'),    
    
    #config for blog modules
    url(r'^blog/',include('blog.urls',namespace='blog')),
      
    #config for tool modules
    url(r'^tool/',include('tool.urls',namespace='tool')),  

    url('^dh$','dh.views.dh'),   

    
)



tool/urls.py
from django.conf.urls import url

from tool import views


urlpatterns = [
    url(r'^$',views.list,name='list'),
    url(r'^(?P<tool_id>[0-9]+)/$',views.detail,name='detail'),
]

blog/models.py
#coding=utf-8
from django.db import models

from public.models import Tag
from django.template.defaultfilters import default


class Category(models.Model):
    name=models.CharField(max_length=20)
    
    def __unicode__(self):
        return self.name
    
class Author(models.Model):
    name=models.CharField(max_length=30)
    email=models.CharField(max_length=30,blank=True)
    website=models.CharField(max_length=50,blank=True)
    
    def __unicode__(self):
        return u'%s' % (self.name)
    
class Article(models.Model):
    caption=models.CharField(max_length=50)
    subcaption=models.CharField(max_length=200,blank=True)
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    author=models.ForeignKey(Author)
    category=models.ForeignKey(Category)
    tags=models.ManyToManyField(Tag,blank=True)
    content=models.TextField()    
    readcount=models.IntegerField(default=0)
    ispublic=models.BooleanField('公开发布',default=1)
    
    def __unicode__(self):
        return u'%s - %s - %s' % (self.caption,self.author,self.update_time.strftime("%Y-%m-%d %H:%I:%S"))
    

index/models.py
from django.db import models

class Block(models.Model):
	name = models.CharField(max_length=50)
	description = models.CharField(max_length=500)
	url=models.CharField(max_length=100)

	def __unicode__(self):
		return self.name

tool/models.py
#coding:utf-8
from django.db import models

from public.models import Tag


class Tool(models.Model):
    name=models.CharField(max_length=50)
    summary=models.CharField(max_length=200)
    description=models.TextField()
    logo=models.ImageField(upload_to='photos')
    picture=models.ImageField(upload_to='photos')   
    url=models.CharField(max_length=200)
    tags=models.ManyToManyField(Tag,blank=True)
    
    def __unicode__(self):
        return self.name

blog/views.py
#coding=utf-8
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.http import Http404

from blog.models import Article, Category


def list(request):
    
    all_articles = Article.objects.all().order_by("-publish_time")
    
    categorys=Category.objects.all()
    
    for category in categorys:
        category.article_num = 0
        for article in all_articles:
            if article.category == category:
                category.article_num += 1
        category.save()
        
    categoryid = request.GET.get('categoryid')   
    if categoryid:
        all_articles = all_articles.filter(category__id=int(categoryid))
    if not request.user.is_authenticated():
        all_articles=all_articles.filter(ispublic=1)
 
    p = Paginator(all_articles , 7)
    
    try:
        page = int(request.GET.get('page',1))
        if page < 1:
            page = 1
    except ValueError:
        page = 1  
        
    try:
        articles = p.page(page)
    except PageNotAnInteger: 
        articles = p.page(1)
    except EmptyPage: 
        articles = p.page(p.num_pages)
        
    after_range_num = 3
    before_range_num = 2
     
    if page >= after_range_num:
        page_range = p.page_range[page - after_range_num:page + before_range_num]
    else:
        page_range = p.page_range[0:page + before_range_num]        
        
    page_title = "软件测试博客"
    return render_to_response('blog/list.html',locals())

def detail(request,article_id):
    try:
        article = Article.objects.get(id=article_id)
        article.readcount+=1
        article.save()
        tags=article.tags.all()
        page_title=article.caption 
    except Article.DoesNotExist:
        raise Http404("文章不存在!")
    if article.ispublic==0 and (not request.user.is_authenticated()):
        raise Http404("权限不足！请登录后重试")
    return render_to_response('blog/detail.html', locals(),context_instance=RequestContext(request))


dh/views.py
#coding=utf-8

from django.shortcuts import render_to_response

def dh(req):
	return render_to_response("dh/dh.html",locals())

index/views.py
from django.shortcuts import render_to_response
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from index.models import Block
from blog.models import Article,Category

def index(req):
	blocks=Block.objects.all().order_by("-id")

	all_articles = Article.objects.all().order_by("-publish_time")

	categorys=Category.objects.all()
    
	for category in categorys:
		category.article_num = 0
		for article in all_articles:
			if article.category == category:
				category.article_num += 1
		category.save()

	
	if not req.user.is_authenticated():
		all_articles=all_articles.filter(ispublic=1)
	p = Paginator(all_articles , 10)
	articles = p.page(1) 

	rank_articles=Article.objects.all().order_by("-readcount")[:10]       

	return render_to_response("index/index.html",locals())

tool/views.py
#coding=utf-8
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.http import Http404

from tool.models import Tool
from public.models import Tag


def list(request):
    all_tools = Tool.objects.all().order_by("-id")

    total_num=len(all_tools)
    
    tags=Tag.objects.filter(use_range__in=[Tag.RANGE_ALL,Tag.RANGE_TOOL_ONLY])

    for tag in tags:
        tag.tool_num=len(tag.tool_set.all())
        tag.save()

    tagid = request.GET.get('tagid')  
    if tagid:
        # 从request中获取的tagid为字符型变量，需要转为int型，
        # 否则在template中无法与tag.id做equal判断
        tagid=int(tagid) 
        
        all_tools = Tag.objects.get(id=tagid).tool_set.all().order_by("-id")
        

    
    p = Paginator(all_tools , 7)
    
    try:
        page = int(request.GET.get('page',1))
        if page < 1:
            page = 1
    except ValueError:
        page = 1  
            
    try:
        tools = p.page(page)
    except PageNotAnInteger: 
        tools = p.page(1)
    except EmptyPage: 
        tools = p.page(p.num_pages)
        
    after_range_num = 3
    before_range_num = 2
     
    if page >= after_range_num:
        page_range = p.page_range[page - after_range_num:page + before_range_num]
    else:
        page_range = p.page_range[0:page + before_range_num]

    page_title="软件测试工具"

    return render_to_response('tool/list.html', locals())

def detail(request,tool_id):

    total_num=len(Tool.objects.all())

    try:
        tool = Tool.objects.get(id=tool_id)

        tags=tool.tags.filter(use_range__in=[Tag.RANGE_ALL,Tag.RANGE_TOOL_ONLY])
        for tag in tags:
            tag.tool_num=len(tag.tool_set.all())
            tag.save()
 
        page_title=tool.name
    except Tool.DoesNotExist:
        raise Http404("工具不存在！")

    return render_to_response('tool/detail.html', locals(),context_instance=RequestContext(request))


blog/templates/article_detail.html
{% extends "base.html" %}
{% block active-blog %}
  	class="active"
{% endblock %}


{% block css %}
    <!-- Custom styles for this template -->
    <link href="/static/css/blog.css" rel="stylesheet">
    <link href="/static/js/syntaxhighlighter/styles/shCore.css" type="text/css" rel="stylesheet"/>
	<link href="/static/js/syntaxhighlighter/styles/shThemeDjango.css" type="text/css" rel="stylesheet"/>
{% endblock %}

{% block js %}
	<script src="/static/js/jquery.min.js"></script>    
	<script type="text/javascript" src="/static/js/scrollTop.js"></script>

	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shCore.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushPython.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushJava.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushCss.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushXml.js"></script>
	<!--
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushSql.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushJScript.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushCpp.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushPerl.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushBash.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushCSharp.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushPhp.js"></script>
	<script type="text/javascript" src="/static/js/syntaxhighlighter/scripts/shBrushPerl.js"></script>
	-->
<script  type = "text/javascript">
	SyntaxHighlighter.all();
    SyntaxHighlighter.defaults['toolbar'] = false;
</script>
{% endblock %}

{% block content %}

    <div class="container "> 
    	<div class="row">
			<div class="blog-main">
			<div class="blog-post">	 
				<p/> 

      			<hr>
	    		<div class="blog-post-title col-sm-11">{{ article.caption }}</div> 	    		
	    		<div class="col-sm-1">
	    			<p><a class="btn btn-success" href="{% url 'blog:list' %}" role="button">&laquo; 返回</a></p>
		        </div>

		     	<div class="col-sm-8">
      				<hr>
		     		<PRE>{{ article.content|safe }}</PRE>
		     	</div>

		     	<div class="col-sm-3 sol-sm-off-1">
		     		<p class="blog-post-meta">作者：<a href="#">{{ article.author }}</a> 
		     		<p class="blog-post-meta">
	      					分类：<a href="../?categoryid={{ article.category.id }}"><span class="label label-primary">{{ article.category }}</span></a> 
	      			</p>
	      			<p class="blog-post-meta">发表时间：{{ article.publish_time|date:"Y-m-d H:i" }} </p>
	      			<p class="blog-post-meta">阅读:({{article.readcount}})</p> 
	      			<p class="blog-post-meta">标签:
	      				{% for tag in tags%}
			                <a class="tag"href="../?tagid={{ tag.id }}" title="{{tag.tag_name}}">{{tag.tag_name}}</a>
			            {%endfor%}
			        </p> 
		     	</div>
	    	</div>
	    	</div>
	    </div>
	    <div class="row">
	    	{% load duoshuo_tags %}
			{% duoshuo_comments %}
		</div>
  	</div>
{% endblock %}

{%block page_footer%}
    <div class="gotop btn btn-success" id="gotobg" title="回到顶部">&and;</div>
{% endblock %}

blog/templates/article_list.html
{% extends "base.html" %}
{% block active-blog %}
  class="active"
{% endblock %}


{% block css %}
    <!-- Custom styles for this template -->
    <link href="/static/css/blog.css" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js"></script>    
    <script src="/static/js/scrollTop.js"></script>    
{% endblock %}

{% block content %}


    <div class="container">
      <div class="row">
        <div class="col-sm-8 blog-main">

          <p/> 
          
          {% for article in articles%}          
            <hr>
            <div class="blog-post">
              <h2 class="blog-post-title"><a href="{% url 'blog:detail' article.id %}">{{ article.caption }}</a></h2>
              
                <div class="blog-post-meta">
                  <div class="left">{{ article.publish_time|date:"Y-m-d H:i" }} by {{ article.author }}</div>

                  <div class="right">阅读({{ article.readcount}})</div>
                </div>
            
              <pre>
                {{ article.content|safe|truncatechars_html:400}} 
	            </pre> 

	          </div><!-- /.blog-post -->
          {% endfor%}

          <nav>
            <ul class="pager">
              	{% if articles.has_previous %}
			    	      <li><a href="?page={{ articles.previous_page_number }}">前一页</a></li>
      			    {% else %}
      			    	<li><a class="active">前一页</a></li>
      			    {% endif %}
      			
      			    {% for p in page_range %}
      			      {% ifequal p page %}
      			      	<li><a class="active">{{p}}</a></li>
      			      {% else %}
      			      	<li><a href="?page={{p}}" title="第{{p}}页">{{p}}</a><li>
      			      {% endifequal %}
      			    {% endfor %}
      			
      			    {% if articles.has_next %}
      			    	<li><a href="?page={{ articles.next_page_number }}">后一页</a></li>
      			    {% else %}
      			    	<li> <a class="active">后一页</a></li>
      			    {% endif %}
            </ul>
          </nav>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <p/>
          <div class="sidebar-module sidebar-module-inset">
            <h4>关于作者</h4>
            <p>七年软件测试相关经验。从事软件测试、软件测试工具研发、软件测试信息系统研发，写过web系统、当过项目经理、带过研发团队。</p>
            <p>主要语言：java、python。</p>
          </div>

          <div class="sidebar-module">
            <h4>文章分类</h4>
            <ul class="list-unstyled">
             	{% for category in categorys %}
              		<li><a href="?categoryid={{ category.id }}">{{category.name}}&nbsp;&nbsp;<span class="badge">&nbsp;{{category.article_num}}&nbsp;</span></a></li>
          		{% endfor%}
            </ul>
          </div>

          <div class="sidebar-module">
            <h4>相关链接</h4>
            <ol class="list-unstyled">
              <li><a target="_blank" href="https://github.com/buaawp" ><img src="/static/images/web-icon/github.ico" /> GitHub</a></li>
              <li><a target="_blank" href="http://cn.linkedin.com/in/buaawp"><img src="/static/images/web-icon/linkedin.ico" /> LinkedIn</a></li>
            </ol>
          </div>          
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->



  

    <footer class="blog-footer">      
      <p>
        
      </p>
    </footer>

  </div>

{% endblock %}

{%block page_footer%}
    <div class="gotop btn btn-success" id="gotobg" title="回到顶部">&and;</div>
{% endblock %}

index/templates/index.html
{% extends "base.html" %}
{% block active-index %}
  class="active"
{% endblock %}


{% block css %}
    <link href="/static/css/index.css" rel="stylesheet">
{% endblock %}


{% block js %}
<script src="/static/js/jquery.min.js"></script>    
<script src="/static/js/scrollTop.js"></script> 

<script  type="text/javascript">
	try {
	    if (window.console && window.console.log) {
	        console.log("author: wang peng\ne-mail:buaawp@gmail.com");
	        console.log("\"Talk is cheap , show me the code\"");	        
	        console.log("@2015 leettest\n")
	    }
	} catch(e) {
	
	}
</script>

{% endblock %}

{% block content %}

<div class ="container">
  <div class="col-md-8">
        <div class="row topbox">
          {% for block in blocks%}
            <div class="col-md-4 topblock">      
              <h2>{{block.name}}</h2>
              <p>{{block.description}}</p>
              <p><a class="btn btn-primary" href="{{block.url}}" role="button">View details &raquo;</a></p>
            </div>
          {% endfor%}
        </div>  

        <div class="row contentbox">
        {% for article in articles%}          
            <div class="contentblock">
              <div class="category">{{ article.category.name }}</div>
              <h3 ><a href="{% url 'blog:detail' article.id %}">{{ article.caption }}</a></h3>              
                <div class="contentblock-meta" >{{ article.publish_time|date:"Y-m-d H:i" }} by {{ article.author }} | 阅读({{ article.readcount}})</div>
                 
                {{ article.content|safe|truncatechars_html:200}} 

            </div><!-- /.contentblock -->
          {% endfor%}
          </div>  
  </div>


       <div class="col-md-4 sidebox">

        <div class="sideblock">
          <h3 class="sideblock_top">
            排行榜
          </h3>
          <div class="sideblock_item">
            <ol>
              {% for article in rank_articles%}   
               <span class="ranknum"></span>
                <li><h5><a href="{% url 'blog:detail' article.id %}" title="{{article.caption}}">{{ article.caption|safe|truncatechars_html:25}}</a></h5></li> 
              {% endfor%}
            </ol>
            </div>
         </div>

         <div class="sideblock">
          <h3 class="sideblock_top">
            文章分类
          </h3>
          <div class="sideblock_item">
            <ul>
              {% for category in categorys %}
                  <li><h5><a href="{% url 'blog:list' %}?categoryid={{category.id}}" target="_blank">{{category.name}}&nbsp;&nbsp;<span class="badge">&nbsp;{{category.article_num}}&nbsp;</span></a></h5></li>
              {% endfor%}
            </ul>
            </div>
         </div>

       </div>


  </div>
</div>

{% endblock %}


{%block page_footer%}
    <div class="gotop btn btn-success" id="gotobg" title="回到顶部">&and;</div>
{% endblock %}


index/templates/index/index.html
{% extends "base.html" %}
{% block active-index %}
  class="active"
{% endblock %}


{% block css %}
    <link href="/static/css/index.css" rel="stylesheet">
{% endblock %}


{% block js %}
<script src="/static/js/jquery.min.js"></script>    
<script src="/static/js/scrollTop.js"></script> 

<script  type="text/javascript">
	try {
	    if (window.console && window.console.log) {
	        console.log("author: wang peng\ne-mail:buaawp@gmail.com");
	        console.log("\"Talk is cheap , show me the code\"");	        
	        console.log("@2015 leettest\n")
	    }
	} catch(e) {
	
	}
</script>

{% endblock %}

{% block content %}

<div class ="container">
  <div class="col-md-8">
        <div class="row topbox">
          {% for block in blocks%}
            <div class="col-md-4 topblock">      
              <h2>{{block.name}}</h2>
              <p>{{block.description}}</p>
              <p><a class="btn btn-primary" href="{{block.url}}" role="button">View details &raquo;</a></p>
            </div>
          {% endfor%}
        </div>  

        <div class="row contentbox">
        {% for article in articles%}          
            <div class="contentblock">
              <div class="category">{{ article.category.name }}</div>
              <h3 ><a href="{% url 'blog:detail' article.id %}" target="_blank">{{ article.caption }}</a></h3>              
                <div class="contentblock-meta" >{{ article.publish_time|date:"Y-m-d H:i" }} by {{ article.author }} | 阅读({{ article.readcount}})</div>
                 
                {{ article.content|safe|truncatechars_html:200}} 

            </div><!-- /.contentblock -->
          {% endfor%}
          </div>  
  </div>


       <div class="col-md-4 sidebox">

        <div class="sideblock">
          <h3 class="sideblock_top">
            排行榜
          </h3>
          <div class="sideblock_item">
            <ol>
              {% for article in rank_articles%}   
               <span class="ranknum"></span>
                <li><h5><a href="{% url 'blog:detail' article.id %}" title="{{article.caption}}">{{ article.caption|safe|truncatechars_html:25}}</a></h5></li> 
              {% endfor%}
            </ol>
            </div>
         </div>

         <div class="sideblock">
          <h3 class="sideblock_top">
            文章分类
          </h3>
          <div class="sideblock_item">
            <ul>
              {% for category in categorys %}
                  <li><h5><a href="{% url 'blog:list' %}?categoryid={{category.id}}" target="_blank">{{category.name}}&nbsp;&nbsp;<span class="badge">&nbsp;{{category.article_num}}&nbsp;</span></a></h5></li>
              {% endfor%}
            </ul>
            </div>
         </div>

         <!--  sogou网盟广告 -->
         <div class="sideblock">
            <div class="sideblock_item"  style="margin-left: 20px; padding-top: 20px;">
              <script type="text/javascript">
              var sogou_ad_id=463439;
              var sogou_ad_height=250;
              var sogou_ad_width=300;
              </script>
              <script type='text/javascript' src='http://images.sohu.com/cs/jsfile/js/c.js'></script>
            </div>
        </div>

       </div>


  </div>
</div>

{% endblock %}


{%block page_footer%}
    <div class="gotop btn btn-success" id="gotobg" title="回到顶部">&and;</div>
{% endblock %}


tool/templates/tool/detail.html
{% extends "base.html" %}
{% block active-tool %}
  	class="active"
{% endblock %}


{% block css %}
    <!-- Custom styles for this template -->
    <link href="/static/css/tool.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container "> 
    	<div class="row">
			<div class="tool-main">
				<div class="tool-post">	 
					<p/> 

	      			<hr>
	      			<div class = "row">
		      			<div class="col-sm-2">
		      				<img class="img-rounded" src="{{ tool.logo.url }}" alt="Generic placeholder image" width="80" height="80">
			    		</div>

			    		<div class="tool-post-title col-sm-9">
			    			<p class="text-left">{{ tool.name }}</p>
			    			<p class="text-left"><a href="{{ tool.url }}" target="_blank">{{ tool.url }}</a></p>
			    			<blockquote>
			    				<footer>{{ tool.summary }}</footer>
			    			</blockquote>
			    		</div> 

			    		<div class="col-sm-1">
			    		<p><a class="btn btn-success" href="{% url 'tool:list' %}" role="button">&laquo; 返回</a></p>
				        </div>

		    		</div><!--/.row-->
		    		
		    		<div class="soft_main">

		      			<div class="col-sm-5">
			      			<h3>软件截图</h3>
		      				<img class="img-thumbnail" src="{{ tool.picture.url }}" alt="Generic placeholder image" width="95%" height="95%">
			    		</div>

			      		<div class="col-sm-7">
			      			<h3>详细描述</h3>
					     	<PRE>
					      		<div class="tool_description">{{ tool.description|safe }}</div>
					   		</PRE>
			      			<h3>标签</h3>
						     	<a class="tag"href="{% url 'tool:list' %}" title="全部">全部<em>({{total_num}})</em></a>
			                    {% for tag in tags%}
			                      <a class="tag"href="../?tagid={{ tag.id }}" title="{{tag.tag_name}}">{{tag.tag_name}}<em>({{tag.tool_num}})</em></a>
			                    {%endfor%}
				   		</div>
				   	</div>

		    	</div><!--/.tool-post-->
	    	</div><!--/.tool-main-->
	    </div><!--/.row-->   
	    
	    <div class="row">
	    	{% load duoshuo_tags %}
			{% duoshuo_comments %}
		</div>   
  	</div><!--/.container-->   
{% endblock %}

tool/templates/tool/list.html
{% extends "base.html" %}
{% block active-tool %}
  class="active"
{% endblock %}


{% block css %}
    <!-- Custom styles for this template -->
    <link href="/static/css/tool.css" rel="stylesheet">
{% endblock %}

{% block content %}

  <div class="container">

  <div class="row">


    <h3>软件测试工具</h3>
    <div class="col-sm-3 soft_sidebar">
        <div class="soft_sidebar">
            <div class="submit_a_new_tool"> <a class="btn btn-success" href="#">提交新工具</a> </div>
            <div class="soft_tags">
               <h3>标签</h3>
               <p>
                    <a class="tag{%if not tagid %} tag_cur{%endif%}" href="{% url 'tool:list' %}" title="全部">全部<em>({{total_num}})</em></a>
                    {% for tag in tags%}
                      <a class="tag {% ifequal tagid tag.id %} tag_cur{%endifequal%} " href="?tagid={{ tag.id }}" title="{{tag.tag_name}}">{{tag.tag_name}}<em>({{tag.tool_num}})</em></a>
                    {%endfor%}
               </p>
            </div>
        </div>
    </div>

    <div class="col-sm-9 soft_list">
       
          {% for tool in tools%}
            <div class="soft_box">
              <div><h4>{{ tool.name }}</h4></div>
              <div class="soft_box_front">
                <img src="{{ tool.logo.url }}" alt="">
              </div>
              <div class="soft_box_back">
                <p>{{ tool.summary|safe}}</p>
                <a href="{% url 'tool:detail' tool.id %}" target="_blank">Learn More</a>
              </div>

            </div><!-- /.col-md-4 -->
          {% empty %}
            <h3><em>No Tool Exist In This Tag!</em></h3>
          {% endfor%}  
    </div>

  </div>

    <footer class="tool-footer">      
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

  </div>
 
{% endblock %}

tool/templates/tool_list.html
{% extends "base.html" %}
{% block active-tool %}
  class="active"
{% endblock %}


{% block css %}
    <!-- Custom styles for this template -->
    <link href="/static/css/tool.css" rel="stylesheet">
{% endblock %}

{% block content %}

  <div class="container">

  <div class="row">


    <h3>软件测试工具</h3>
    <div class="col-sm-3 soft_sidebar">
        <div class="soft_sidebar">
            <div class="submit_a_new_tool"> <a class="btn btn-success" href="#">提交新工具</a> </div>
            <div class="soft_tags">
               <h3>标签</h3>
               <p>
                    <a class="tag{%if not tagid %} tag_cur{%endif%}" href="{% url 'tool:list' %}" title="全部">全部<em>({{total_num}})</em></a>
                    {% for tag in tags%}
                      <a class="tag {% ifequal tagid tag.id %} tag_cur{%endifequal%} " href="?tagid={{ tag.id }}" title="{{tag.tag_name}}">{{tag.tag_name}}<em>({{tag.tool_num}})</em></a>
                    {%endfor%}
               </p>
            </div>
        </div>
    </div>

    <div class="col-sm-9 soft_list">
       
          {% for tool in tools%}
            <div class="soft_box">
              <div><h4>{{ tool.name }}</h4></div>
              <div class="soft_box_front">
                <img src="{{ tool.logo.url }}" alt="">
              </div>
              <div class="soft_box_back">
                <p>{{ tool.summary|safe}}</p>
                <a href="{% url 'tool:detail' tool.id %}" target="_blank">Learn More</a>
              </div>

            </div><!-- /.col-md-4 -->
          {% empty %}
            <h3><em>No Tool Exist In This Tag!</em></h3>
          {% endfor%}  
    </div>

  </div>

    <footer class="tool-footer">      
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

  </div>
 
{% endblock %}